### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by chris-martin** [haskell-hvr/rss#10]
Hi, would you consider adding this package to [Stackage](https://github.com/fpco/stackage/) to make it a bit easier to keep up-to-date with the latest dependency versions?

**Comment by hvr** [comment]
Well, quoting https://github.com/haskell-hvr/.github/edit/master/CONTRIBUTING.md :

> ## FAQ
>
> - **Can you add your packages to Stackage?** No can do; [I have been banned from Stackage](https://github.com/fpco/stackage/issues/4472) but if you haven't been blocked yet, you can try to [file an issue](https://github.com/fpco/stackage/issues/new).

**Comment by chris-martin** [comment]
:frowning_face: alright I give up

**Comment by andreasabel** [comment]
See: 
- https://github.com/commercialhaskell/stackage/pull/6544
